### ISSUE TITLE
ModuleNotFoundError: No module named 'google.cloud.datastore_v1.gapic'

### ISSUE THREAD

**Issue by dblakemore** [googleapis/python-datastore#116]
Recently started seeing this error on a python3 appengine project I've been working on. Only noticed the issue today and I believe it is related to the recent new version. For context, I am running my code locally using `dev_appserver.py`, which is temp installing my python 3 requirements at runtime.

In my `requirement.txt` file, I have `google-cloud-ndb==1.7.0` (https://pypi.org/project/google-cloud-ndb/). This packages lists `google-cloud-datastore>=1.7.0` as a dependency (in setup.py), which (as I understand it) is grabbing the most recent version (if google-cloud-datastore is not already installed or is installed at a version lower than 1.7.0). However, in https://github.com/googleapis/python-ndb/blob/master/google/cloud/ndb/client.py, the code has the following import (line 26) `from google.cloud.datastore_v1.gapic import datastore_client`, but this falls over now, because the latest version of `google-cloud-datastore` does not have this file.

The problem is "fixed" by adding `google-cloud-datastore==1.7.3" to the requirements.txt file _before_ `google-cloud-ndb`, but I think this is something that should really be updated in `google-cloud-ndb`'s dependencies.

**Comment by chrisrossi** [comment]
This is a duplicate of this bug in the NDB repo: https://github.com/googleapis/python-ndb/issues/568

Please follow the issue in the NDB tracker for resolution.

**Comment by dblakemore** [comment]
Thanks. I've just realised that I was checking for issues (and raised this one) against the wrong project 🤦 . Closing.
