### ISSUE TITLE
query.fetch() fails if GOOGLE_CLOUD_DISABLE_GRPC is set

### ISSUE THREAD

**Issue by tomthorogood** [googleapis/python-datastore#124]
[This new behavior](https://github.com/googleapis/python-datastore/blob/master/google/cloud/datastore/query.py#L579-L584) causes an error: `run_query() got an unexpected keyword argument 'request'` because when the `GOOGLE_CLOUD_DISABLE_GRPC` environment variable is set (which is a requirement in some runtimes, e.g., [when using gunicorn with gevent](https://github.com/googleapis/google-cloud-python/issues/3486)), the underlying [HTTPDatastoreAPI#run_query](https://github.com/googleapis/python-datastore/blob/master/google/cloud/datastore/_http.py#L183-L185) method does not accept a `request` parameter.

Example:

```python
# run_query.py

from google.cloud import datastore

client = datastore.Client()  # Assuming an auth'd environment
results = [entity for entity in client.query(kind="Foo").fetch()]
```

I feel like this can be fixed by updating the signature for the HTTPDatastoreAPI#run_query to accept `request` and only subsequently build the request object if it's not passed in, so that the signatures match for all implementations.

**Comment by tseaver** [comment]
@tomthorogood Thanks for the report!

@crwilcox We need to set up CI (maybe periodic, rather than precommit?) to exercise the library with `GOOGLE_CLOUD_DISABLE_GRPC` set.

**Comment by crwilcox** [comment]
#133

**Comment by tseaver** [comment]
Note that we have a broader issue here:  *all* of the methods of the `HTTPDatastoreAPI` need to be updated to match the `request`-only pattern of the new GRPC API.

**Comment by tseaver** [comment]
The `HTTPDatastoreAPI` is also missing `reserve_ids`. :(

**Comment by tomthorogood** [comment]
I am so sorry, I only just saw that this was resolved. Thank you so much! I really appreciate it.
