### ISSUE TITLE
Batches in >=2.0.0 are significantly slower

### ISSUE THREAD

**Issue by BinarSkugga** [googleapis/python-datastore#145]
I believe there is a change of API or a performance issue when using batches with 2.1.0.

#### Environment details

  - OS type and version: Windows 10
  - Python version: 3.8.7
  - pip version: 20.3.3
  - `google-cloud-datastore` version: 2.1.0
  - `google-api-core` version: 1.24.1

#### Steps to reproduce

  1. Use DatastoreClient::put_multi with 500 entities inside a batch

#### Code example

```python
with client.batch():
    client.put_multi(chunk)
```

#### Performance
When using 1.15.0, my code can handle 9 batches of 500 entities in about 1-2 seconds while 2.1.0 takes literal minutes.
Disclaimer: I use the datastore emulator

**EDIT**: It can be reproduced in 2.0.0

**Comment by crwilcox** [comment]
Are you seeing this in both emulator and live endpoints?

**Comment by BinarSkugga** [comment]
I haven't tested on a live endpoint. I'm in vacation for the week, I'll definitely test this when I come back.

**Comment by crwilcox** [comment]
Thanks @BinarSkugga . I know we overhauled, rather substantially, the transport layer in the v1 -> v2. It would be very helpful to understand if you are seeing a slowdown on a live endpoint.

**Comment by BinarSkugga** [comment]
I am back from my vacation. I do not experience this behavior with a live endpoint. Should I move the issue to the emulator's repository ?

**Comment by BinarSkugga** [comment]
Additional potentially impactful information:

- The emulator doesn't log any errors.
- I fetch those batches in parrallel using Python's ThreadPoolExecutor from the concurrent package.
- Deleting entities seems also slightly slower but its negligible compared to writes.

**Comment by BinarSkugga** [comment]
I may have talked to fast. It also happens on live endpoints.
Logs from 1.15.x:
`[SOLLUM][DATA][INFO][10:42:35]: Fetching 4130 'LayoutEntity' entities...
[SOLLUM][DATA][VERBOSE][10:42:35]: Using 9 'LayoutEntity' batches...
[SOLLUM][DATA][VERBOSE][10:42:36]: Fetched 'LayoutEntity' batch #1/9
[SOLLUM][DATA][VERBOSE][10:42:36]: Fetched 'LayoutEntity' batch #2/9
[SOLLUM][DATA][VERBOSE][10:42:37]: Fetched 'LayoutEntity' batch #4/9
[SOLLUM][DATA][VERBOSE][10:42:37]: Fetched 'LayoutEntity' batch #3/9
[SOLLUM][DATA][VERBOSE][10:42:37]: Fetched 'LayoutEntity' batch #5/9
[SOLLUM][DATA][VERBOSE][10:42:37]: Fetched 'LayoutEntity' batch #6/9
[SOLLUM][DATA][VERBOSE][10:42:37]: Fetched 'LayoutEntity' batch #7/9
[SOLLUM][DATA][VERBOSE][10:42:37]: Fetched 'LayoutEntity' batch #8/9
[SOLLUM][DATA][VERBOSE][10:42:37]: Fetched 'LayoutEntity' batch #9/9`

Logs from 2.1.x:
`[SOLLUM][DATA][INFO][10:44:15]: Fetching 4130 'LayoutEntity' entities...
[SOLLUM][DATA][VERBOSE][10:44:15]: Using 9 'LayoutEntity' batches...
[SOLLUM][DATA][VERBOSE][10:45:19]: Fetched 'LayoutEntity' batch #1/9`

I was too lazy to wait for the 9 batches here but the point is made. Here's the code that handles this:
`
def _do_execute_action(chunk, client, action, count, total):
    with client.batch():
        action(chunk)
        Loggers.DATA.verbose('Executed batch #{}/{}'.format(count.next(), total))
count = AtomicNumber()
chunked = list(chunks(lst, config.MAX_BATCH_ENTITY))
ConcurrentService.i().thread_each(chunked, _do_execute_action, self.client, action, count, len(chunked))
`

The concurrent service simply submit a new task per batch in the thread pool.

**Comment by BinarSkugga** [comment]
Any insight on this ?

**Comment by crwilcox** [comment]
I have received another customer report. While not quite the difference stated here, 2-3x slower is about what the other instance was observing. It would be good to benchmark a few operations and see if there are any obvious gains that could be made.

**Comment by craiglabenz** [comment]
I've been attempting to recreate this, but so far am seeing more or less similar outcomes for batch operations between versions `2.1.0` and `1.15.3`.

Querying may very well be slower, however.

First test run:

```sh
$ python datastore-test.py                         
[python-datastore@1.15.3] finished creation loop in 5.0 ms
[python-datastore@1.15.3] finished batch write in 1926.0 ms
[python-datastore@1.15.3] finished batch get in 391.0 ms
[python-datastore@1.15.3] finished batch update in 1706.0 ms
[python-datastore@1.15.3] finished batch query in 2216.0 ms
  > loaded 3500 objects
```

Switch to version `2.1.0` and run again:

```sh
python datastore-test.py              
[python-datastore@2.1.0] finished creation loop in 4.0 ms
[python-datastore@2.1.0] finished batch write in 2109.0 ms
[python-datastore@2.1.0] finished batch get in 588.0 ms
[python-datastore@2.1.0] finished batch update in 1701.0 ms
[python-datastore@2.1.0] finished batch query in 3702.0 ms
  > loaded 4000 objects
```

I will continue to investigate, but for now, [here's the testing script I'm using](https://gist.github.com/craiglabenz/420fff466db1e2608b3000556c322f4a).
