### ISSUE TITLE
Datastore Model class

### ISSUE THREAD

**Issue by gnagel** [googleapis/python-datastore#148]
Hi!

Are there any plans to add support for a Model class similar to the `ndb.Model` class similar to `google.appengine.ext.ndb.Model`?

For example this one from the docs: https://github.com/GoogleCloudPlatform/python-docs-samples/blob/6f5f3bcb81779679a24e0964a6c57c0c7deabfac/appengine/standard/ndb/entities/snippets.py#L15-L21

```py
from google.appengine.ext import ndb


class Account(ndb.Model):
    username = ndb.StringProperty()
    userid = ndb.IntegerProperty()
    email = ndb.StringProperty()

```

Thanks!
Glenn

**Comment by gnagel** [comment]
Hi @craiglabenz ,

I'm happy to add this to `python-datastore` my self if this is something you would be open to PR reviewing.

Let me know what you think!

Glenn

**Comment by gnagel** [comment]
@dmahugh / @craiglabenz - What do you think about this one?

> I'm happy to add this to `python-datastore` myself if this is something you would be open to PR reviewing.

**Comment by chrisrossi** [comment]
Hi @gnagel ,

NDB has been ported to Google Cloud. See [here](https://cloud.google.com/appengine/docs/standard/python3/migrating-to-cloud-ndb).

The GitHub repo for Google Cloud NDB is [here](https://github.com/googleapis/python-ndb).

**Comment by gnagel** [comment]
You rock @chrisrossi !  

Thanks :-)
