### ISSUE TITLE
Add a py.typed file for submodule

### ISSUE THREAD

**Issue by crwilcox** [googleapis/python-datastore#240]
To be in accordance with [PEP 561](https://www.python.org/dev/peps/pep-0561/) we should add a py.typed file to google/cloud/datastore/py.typed

The file can be empty but does need to be present for some type checkers.

**Comment by tseaver** [comment]
I have a WIP locally which passes.

```bash
$ .nox/mypy/bin/mypy google/ tests
Success: no issues found in 66 source files
```

In addition to tweaking `noxfile.py` to install additional `types-*` packages, I needed to apply the changes which should be generated by these two `gapic-generator-python` PRs:

- https://github.com/googleapis/gapic-generator-python/pull/1065
- https://github.com/googleapis/gapic-generator-python/pull/1066

However, there is another issue which is un-addressed by those PRs:  the generated code for the `datastore_admin_v1` clients declares invalid / unknown types for the `labels` parameters to `import_entities` and `export_entites`:

```bash
$ .nox/mypy/bin/mypy google/
google/cloud/datastore_admin_v1/services/datastore_admin/client.py:384: error: Name "datastore_admin.ExportEntitiesRequest.LabelsEntry" is not defined
google/cloud/datastore_admin_v1/services/datastore_admin/client.py:523: error: Name "datastore_admin.ImportEntitiesRequest.LabelsEntry" is not defined
google/cloud/datastore_admin_v1/services/datastore_admin/async_client.py:209: error: Name "datastore_admin.ExportEntitiesRequest.LabelsEntry" is not defined
google/cloud/datastore_admin_v1/services/datastore_admin/async_client.py:347: error: Name "datastore_admin.ImportEntitiesRequest.LabelsEntry" is not defined
```

By my reading of the [protobuf definition](), those parameters shohttps://github.com/googleapis/googleapis/blob/0c2e4540e01637d1964d141e68e8cd20619e4c6e/google/datastore/admin/v1/datastore_admin.proto#L262-L322uld be typed as `Dict[str, str]`, and in fact that makes `mypy` happy.

**Comment by tseaver** [comment]
The `LabelsEntry` bug is due to https://github.com/googleapis/gapic-generator-python/issues/689.
