### ISSUE TITLE
Datastore: Allow retry and timeout configuration on a per instance level

### ISSUE THREAD

**Issue by Subaku** [googleapis/python-datastore#3]
Seems the configuration for these two items are buried in the code and can't be configured on a per use basis. When debugging connectivity issues the default timeout takes forever and would love to set a shorter timeout on my calls to `query.fetch(...)` for example.

Or perhaps I've missed something in the docs?

**Comment by tseaver** [comment]
Sketch of implementation:

- Add `retry` and `timeout` args to `Client.allocate_ids`, and plumb through to the underlying RPC.
- Add `retry` and `timeout` args to `Client.reserve_ids`, and plumb through to the underlying RPC.
- Add `retry` and `timeout` args to `Batch.commit` and plumb through to the underlying RPC in `_commit`
- Add `retry` and `timeout` args to `Transaction.begin`, and plumb through to the underlying RPC.
- Add `retry` and `timeout` args to `Transaction.rollback`, and plumb through to the underlying RPC.
- Add `retry` and `timeout` args to `query.Iterator` ctor, and plumb through to the underlying RPC in `_next_page`.
- Add `retry` and `timeout` args to `Query.fetch`, and plumb through to the iterator ctor.
