### ISSUE TITLE
Unit tests are not run against python3.8

### ISSUE THREAD

**Issue by tsukasa-au** [googleapis/python-datastore#31]
Thanks for stopping by to let us know something could be better!

#### Environment details

  - OS type and version: Arch linux
  - Python version: `3.8.2`
  - pip version: `20.0.2` (installed in virtual env)
  - `google-cloud-datastore` version: `master`

#### Steps to reproduce

  1. Run unit tests on machine with only python3.8 installed
  2. Tests don't run

NOTE: This issue is being created so that it can be attached to a PR.

**Comment by HemangChothani** [comment]
@tsukasa-au `Python3.8` has added in the `nox.py` file for unit testing, so closing this issue.  

https://github.com/googleapis/python-datastore/blob/1963fd84c012cc7985e44ed0fc03c15a6429833b/noxfile.py#L31
