### ISSUE TITLE
Error when importing from google.cloud import datastore

### ISSUE THREAD

**Issue by SaschaHeyer** [googleapis/python-datastore#35]
Hi Folks,

when importing from google.cloud import datastore we are getting the following error.

from google.cloud import datastore
AttributeError: module 'grpc.experimental.aio' has no attribute 'UnaryUnaryCall'
Using the following version google-cloud-datastore==1.10.0

Is this a known issue?

#### Environment details

  - OS type and version: /
  - Python version: python 3.7
  - pip version: `20.0.2`
  - `google-cloud-datastore` version: 1.10.0

#### Steps to reproduce

  1. import datastore

#### Code example

```python
from google.cloud import datastore
```

#### Stack trace
```
```

**Comment by HemangChothani** [comment]
@SaschaHeyer any update from your side? I am still not able to reproduce this issue.

**Comment by tseaver** [comment]
Please follow-up / reopen if you can provide more information.
