### ISSUE TITLE
Datastore: hitting "400 operating on too many entity groups in single transaction" with datastore emulator 

### ISSUE THREAD

**Issue by artoale** [googleapis/python-datastore#4]
Hello,

while working on a Django connector to support the Cloud Firestore in Datastore mode, we encountered this issue when trying to upsert more than 25 entities in a single transaction:

```google.api_core.exceptions.InvalidArgument: 400 operating on too many entity groups in a single transaction.```

Which as far as I can tell should no longer be a limitation. 

#### Environment details
Datastore emulator: SDK v272.0.0
Python v3.7.4
google-cloud-datastore v1.9.0

#### Steps to reproduce

Create 26 or more entities then, in a single transaction, update them 

#### Code example

```python
with client.transaction():
  for key in keys:
    entity = client.get(key)
    entity.update(...)
    client.put(entity)
```

I couldn't find a repo specific for the emulator, please let me know if there's a better place where to report this issue.

Thanks

**Comment by rotemvilsa** [comment]
Hey,

Is there anything new about this issue? Finding myself and my team having a really hard time emulating Firestore in Datastore Mode features such as not having the 25 entity groups limit.  

Thanks

**Comment by tseaver** [comment]
There isn't anything we can do from the `google-cloud-datastore` library to fix a limit being imposed by the emulator.  Please refer to the [datastore support page](https://cloud.google.com/datastore/docs/getting-support) for options.
