### ISSUE TITLE
google.api_core.exceptions.ResourceExhausted: 429 Received message larger than max (11915495 vs. 4194304)

### ISSUE THREAD

**Issue by HemangChothani** [googleapis/python-datastore#40]
-  Facing the error when try to run the `system tests` against the  emulator.

- System tests are related to `LargeCharacterEntity`

- Related issue in pubsub https://github.com/googleapis/python-pubsub/issues/3

**Comment by tseaver** [comment]
@HemangChothani Can you post the full traceback, please?

**Comment by tseaver** [comment]
This is likely an issue with the emulator itself, rather than with the Python library.

**Comment by HemangChothani** [comment]
@tseaver Yes, the issue is related to emulator limitation.

**Comment by anguillanneuf** [comment]
gcloud's recent 313.0.0 release [increased message size in the emulator](https://cloud.google.com/sdk/docs/release-notes#pubsub_emulator). The max message size is 10 MiB now. Thanks for your patience!
