### ISSUE TITLE
Question: What happened to TransactionFailedError?

### ISSUE THREAD

**Issue by maininformer** [googleapis/python-datastore#46]
Hello. 

I am migrating appengine 1 code, and there are places where we depend on [TransactionFailedError](https://github.com/theosp/google_appengine/blob/9ce87a20684dc99cf5968e6f488c060e1530c159/google/appengine/ext/db/__init__.py#L116). I noticed there are no such named exceptions in this client code. I need to know what the intentions were here so I can make a correct decision; could you please help me understand the reasoning for the existence and non-existence of this exception? Do you have a suggestion on catching such an incident? Thank you.

(Same for others like `BadArgumentError` etc)

**Comment by tseaver** [comment]
@chrisrossi, @cguardia I know y'all wrestled with similar issues during the NDB reimplementation.  Can you provide pointers?

**Comment by chrisrossi** [comment]
I don't know that I have a lot of insight, in general, about why exceptions were changed for the Cloud versions of various APIs, but I do know that in the course of working with NDB we figured out that `google.api_core.exceptions.Aborted` basically means the transaction failed, so I think that is probably a reasonable substitute for `TransactionFailedError`. 

We discussed this exception and its implications for NDB, [here](https://github.com/googleapis/python-ndb/pull/391#issuecomment-614835220).

**Comment by plumSemPy** [comment]
Thanks @chrisrossi. You folk can't get a break from me can you 😄 . 

How do you all suggest I go about this short of opening an issue for the history of each deprecated exception?

**Comment by Mariatta** [comment]
It seems like the question about TransactionFailedError has been answered. If you have question about other specific error please open a new ticket. Thanks.
