### ISSUE TITLE
Headers are not the same between DatastoreAsyncClient and DatstoreClient

### ISSUE THREAD

**Issue by mahdilamb** [googleapis/python-datastore#544]
The requests to the `DatastoreAsyncClient` currently fail as the headers do not contain the `database_id`. In the `DatastoreClient`, these are added.

**Comment by daniel-sanche** [comment]
Thanks for the report

The `datastore_v1` files are all autogenerated, so we have to address this in the generation pipeline. I [opened a bug](https://github.com/googleapis/gapic-generator-python/issues/2091) to fix this there

**Comment by daniel-sanche** [comment]
This has been [fixed upstream](https://github.com/googleapis/gapic-generator-python/issues/2091). We should be able to merge in the fix and get it in the next release
