### ISSUE TITLE
Datastore: Add support for creating a database with option for choosing modes.

### ISSUE THREAD

**Issue by himanshu219** [googleapis/python-datastore#8]
Currently there is no way to create a database in datastore via APIs and customers find it frustrating to go to the console create a database choose the mode in their project.

It would be good if we can automate this and provide APIs so that one can achieve this via gcloud sdk, python sdk etc.

**Comment by tseaver** [comment]
Even with the addition of the Datastore Admin Client in PR #39, there is still no way for this library to bootstrap enabling the Datastore API itself.
